Add UI
rbd3/School-Library pull request #4
Opened 2023-08-31 13:34 UTC by rbd3

### Change made:
👉 Add app.rb
👉 Add main.rb

2023-08-31 16:40 UTC, iambenkis requested changes
#### Hi @rbd3 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
You did a great job, keep up the good work 👍🏼

![giphy](https://user-images.githubusercontent.com/25227022/169391888-8dd8108f-0d42-4e54-87cc-a3f9fd392dbc.gif)


## Highlights

✔️  Can create Teacher
✔️ Can create Book 
✔️  Can print list of Book and Person 

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-08-31 16:40 UTC, iambenkis commented on app.rb
> +
- [ ] Good job creating a basic UI for your app, However , I once I wanted to create Student , He could not be saved in the `students` variable 👍 ,even though no exception was thrown 😄 . Kindly ensure that I can create a student in your app 👍

2023-08-31 16:40 UTC, iambenkis commented on app.rb
> +  end
- [ ] Also for `Rental`, once I wanted to create a Rental based on `Book` and `Person` , It was thrown the following exception 😢 , Kindly fix that and ensure the creation of a `Rental` is enabled 👍  

![Capture](https://github.com/rbd3/School-Library/assets/80458199/62a6d28c-38f0-4afb-89e5-29b6c630d277)

2023-09-01 13:54 UTC, BregornOriginal requested changes
Hi @rbd3  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![giphy (4)](https://github.com/rbd3/School-Library/assets/93630700/2ddb2589-3d10-4ef0-b68b-19795a0d5de8)

## Highlights

✅ Linters are passing
✅ Good commit history
✅ Excellent work implementing rentals 💯 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 13:54 UTC, BregornOriginal commented on app.rb
> +        puts "Number: #{i + 1}, Name: #{person.name}, age: #{person.age}, ID: #{person.id}"
- [ ] Kindly fix the UI where you list people created. There's an error where `name` it's equal to the `parent_permission` and not to the name of the person created

![image](https://github.com/rbd3/School-Library/assets/93630700/9dd0c86d-31cb-43e3-911f-4d49a4f35c8e)

2023-09-01 16:04 UTC, cynthiainga approved these changes
Hi @rbd3, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] All requested changes are made ✔️ 
- [ ] Correct Gitflow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 16:20 UTC, merged